name: symfony8-2305
volumes:
  db_data: {}
services:
  db: 
    image: mariadb:10.8.5
    container_name: symfony8-2305-db
    restart: unless-stopped
    ports: ["3307:3306"]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_symfony
      MYSQL_USER: user_symfony 
      MYSQL_PASSWORD: azer
  web: 
    # image: php:8.4-apache
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: symfony8-2305-web
    restart: unless-stopped
    ports: ["9000:80"]
    depends_on: ['db']
    links: ['db']
    volumes:
      - ./src:/var/www/html

